theme: jekyll-theme-hacker
title: root💀King0Root-sec:~#
description: Hack Enumerate Harder!. Eat. Sleep. Repeat.
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap
